branch-defaults:
  default:
    environment: pando-3d-dev
    group_suffix: null
  master:
    environment: pando-3d-dev
global:
  application_name: pando-3d
  default_ec2_keyname: aws-eb-pando3d
  default_platform: Python 2.7
  default_region: eu-west-1
  profile: default
  sc: git
